'use server';
/**
 * @fileOverview This file defines a Genkit flow for generating and executing JavaScript code
 * within a secure sandbox.
 *
 * - generateAndExecuteCode - A function that orchestrates code generation and execution.
 * - CodeGenerationInput - The input type for the generateAndExecuteCode function.
 * - CodeExecutionOutput - The return type for the generateAndExecuteCode function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { VM } from 'vm2'; // Assuming vm2 is available in the Node.js environment

const MAX_CODE_LENGTH = 5000;
const MAX_OUTPUT_LENGTH = 2000;
const EXECUTION_TIMEOUT_MS = 5000; // 5 seconds

// Input schema for the code generation request
const CodeGenerationInputSchema = z.object({
  problemDescription: z
    .string()
    .max(500)
    .describe('A detailed description of the problem or task for which JavaScript code needs to be generated and executed.'),
});
export type CodeGenerationInput = z.infer<typeof CodeGenerationInputSchema>;

// Output schema for the code execution result
const CodeExecutionResultSchema = z.object({
  output: z.string().max(MAX_OUTPUT_LENGTH).describe('The standard output from the JavaScript code execution.'),
  success: z.boolean().describe('True if the code executed successfully, false otherwise.'),
  error: z.string().optional().describe('An error message if execution failed.'),
  executionTime: z.number().describe('The time taken for execution in milliseconds.'),
});
export type CodeExecutionResult = z.infer<typeof CodeExecutionResultSchema>;

// Output schema for the entire flow
const CodeGenerationAndExecutionOutputSchema = z.object({
  generatedCode: z.string().max(MAX_CODE_LENGTH).describe('The JavaScript code generated by the AI.'),
  executionResult: CodeExecutionResultSchema.describe('The result of executing the generated JavaScript code.'),
});
export type CodeGenerationAndExecutionOutput = z.infer<typeof CodeGenerationAndExecutionOutputSchema>;

// Define a Genkit tool for running JavaScript code in a sandbox
const runJavaScriptCodeTool = ai.defineTool(
  {
    name: 'runJavaScriptCode',
    description:
      'Executes provided JavaScript code in a secure sandboxed environment. Use this tool for complex calculations, data processing, and solving algorithmic challenges. Capture console.log output.',
    inputSchema: z.object({
      code: z.string().max(MAX_CODE_LENGTH).describe('The JavaScript code to execute.'),
    }),
    outputSchema: CodeExecutionResultSchema,
  },
  async ({ code }) => {
    let stdout = '';
    let success = false;
    let error: string | undefined = undefined;
    const startTime = Date.now();

    try {
      // Ensure code length limit is respected
      if (code.length > MAX_CODE_LENGTH) {
        throw new Error(`Code exceeds maximum allowed length of ${MAX_CODE_LENGTH} characters.`);
      }

      const vm = new VM({
        timeout: EXECUTION_TIMEOUT_MS,
        sandbox: {
          // Whitelisted globals
          Math,
          JSON,
          Array,
          String,
          Number,
          Date,
          // Custom console object to capture logs
          console: {
            log: (...args: any[]) => {
              stdout += args.map(String).join(' ') + '\n';
            },
            error: (...args: any[]) => {
              stdout += `ERROR: ${args.map(String).join(' ')}\n`;
            },
            warn: (...args: any[]) => {
              stdout += `WARN: ${args.map(String).join(' ')}\n`;
            },
            info: (...args: any[]) => {
              stdout += `INFO: ${args.map(String).join(' ')}\n`;
            },
          },
        },
        // Block `require`, `process`, `fs`, `net`, `http`, `eval` by default for security
        require: false, // Explicitly disable require
        allowAsync: false, // Disallow async functions in sandbox for simpler control
      });

      vm.run(code);
      success = true;
    } catch (e: any) {
      error = e.message || 'Unknown execution error.';
    } finally {
      const executionTime = Date.now() - startTime;
      // Truncate output if it exceeds max length
      if (stdout.length > MAX_OUTPUT_LENGTH) {
        stdout = stdout.substring(0, MAX_OUTPUT_LENGTH) + '\n... (output truncated)';
      }
      return {
        output: stdout,
        success,
        error,
        executionTime,
      };
    }
  }
);

// Define a Genkit prompt for generating JavaScript code
const generateCodePrompt = ai.definePrompt({
  name: 'generateCodePrompt',
  input: { schema: CodeGenerationInputSchema },
  output: { schema: z.object({ generatedCode: z.string() }) }, // Output only the code
  tools: [runJavaScriptCodeTool], // Make the tool available to the model if it needs to simulate execution
  prompt: `You are an expert JavaScript programmer. Your task is to write a JavaScript code snippet that solves the given problem.
The code should be self-contained and not rely on external libraries unless explicitly stated in the problem.
If the problem asks for output, use console.log() to produce it.
Return only the JavaScript code, without any additional explanations, comments, or markdown formatting (e.g., no \`\`\`javascript).
Keep the code concise and efficient.

Problem Description: {{{problemDescription}}}`,
});

// Define the main Genkit flow for AI code generation and execution
const codeGenerationAndExecutionFlow = ai.defineFlow(
  {
    name: 'codeGenerationAndExecutionFlow',
    inputSchema: CodeGenerationInputSchema,
    outputSchema: CodeGenerationAndExecutionOutputSchema,
  },
  async (input) => {
    // Step 1: Generate JavaScript code based on the problem description
    const { output: codeOutput } = await generateCodePrompt(input);
    const generatedCode = codeOutput!.generatedCode;

    // Step 2: Execute the generated code using the defined tool
    const executionResult = await runJavaScriptCodeTool({ code: generatedCode });

    // Step 3: Return the generated code and its execution result
    return {
      generatedCode,
      executionResult,
    };
  }
);

/**
 * Orchestrates the generation and execution of JavaScript code by an AI agent.
 *
 * @param input - The problem description for which code needs to be generated and executed.
 * @returns The generated JavaScript code and the result of its execution.
 */
export async function generateAndExecuteCode(
  input: CodeGenerationInput
): Promise<CodeGenerationAndExecutionOutput> {
  return codeGenerationAndExecutionFlow(input);
}
